### ISSUE TITLE
Can we dive deeper into the analysis related to in-silico perturbation?

### ISSUE THREAD

**Issue by HelloWorldLTY** [mcgilldinglab/UNAGI#1]
Hi, thanks for your great work! I am superly interested in your research related to in-silico perturbation, but it seems that I cannot find related descriptions in the tutorial folder. Would you please provide a notebook related to this step? Thanks!

**Comment by Szym29** [comment]
Hi, 

Thanks for your interest in our project. We are actively working to improve the usability of UNAGI and more tutorials will be available later on. 

Would you mind letting us know the parts that you are particularly interested in doing in-silico perturbation? For general perturbation usage, you can probably check our [documentation web page](https://unagi-docs.readthedocs.io/en/latest/notebooks/examples/index.html) if you haven't. 

Thanks!

**Comment by HelloWorldLTY** [comment]
Hi, thanks for your quick response. I am more interested in the output of this instruction:

<img width="785" alt="image" src="https://github.com/mcgilldinglab/UNAGI/assets/43333475/f28bc776-315c-424f-a358-41c4ba247ab0">


It seems that you have performed various in-silico perturbation analyses, including the comparisions with real cases. Does the output of this instruction can handle all cases? Thanks.

**Comment by Szym29** [comment]
Sure. We will provide a tutorial specifically for this part. 

For now, we have [a simple example](https://unagi-docs.readthedocs.io/en/latest/notebooks/examples/visualize_UNAGI_results_example_dataset.html#visualize-the-drug-compounds-perturabtion-results) to show the results of our in-silico perturbation. The UNAGI.analyse_UNAGI() function performs a lot of downstream tasks, including performing in-silico perturbation. Running this function may take hours, so we use UNAGI.perturbations.get_top_compounds() and UNAGI.perturbations.get_top_pathways() to retrieve the results of top in-silico perturbations of compounds and pathways.

I will let you know once the updated tutorial is ready. 

Thanks.

**Comment by HelloWorldLTY** [comment]
Hi, thanks for your quick response. I tried to use the example dataset (seems example_1 folder). However, it seems that the reading of files  meets some problems:

```
FileNotFoundError                         Traceback (most recent call last)
Cell In[1], line 7
      5 warnings.filterwarnings('ignore')
      6 PATH_TO_YOUR_DATA = 'your_data.h5ad'
----> 7 adata = sc.read(PATH_TO_YOUR_DATA)

File /gpfs/gibbs/project/zhao/tl688/conda_envs/unagi/lib/python3.9/site-packages/scanpy/readwrite.py:114, in read(filename, backed, sheet, ext, delimiter, first_column_names, backup_url, cache, cache_compression, **kwargs)
    112 filename = Path(filename)  # allow passing strings
    113 if is_valid_filename(filename):
--> 114     return _read(
    115         filename,
    116         backed=backed,
    117         sheet=sheet,
    118         ext=ext,
    119         delimiter=delimiter,
    120         first_column_names=first_column_names,
    121         backup_url=backup_url,
    122         cache=cache,
    123         cache_compression=cache_compression,
    124         **kwargs,
    125     )
    126 # generate filename and read to dict
    127 filekey = str(filename)
```

Did I read the correct file? Thanks.

**Comment by Szym29** [comment]
Hi,

Sorry for the late response. Here in line 6, you have to replace 'your_data.h5ad' with the path of your h5ad file. Thanks.

**Comment by HelloWorldLTY** [comment]
Thanks. Actually my previous question is to check which file should I use  to replace 'your_data.h5ad'. It seems that the example.h5ad does not fit.

Another question is about the tutorial for training:

<img width="952" alt="image" src="https://github.com/mcgilldinglab/UNAGI/assets/43333475/05b3f4fa-5a69-419b-a485-f6c45a31ec2c">

It seem that I cannot create a folder based on this function, is there anything wrong? If I deleted .h5ad. then the next training step will encounter errors.

**Comment by Szym29** [comment]
The example dataset should work. I will push a new version of the source code in the coming days with updated tutorials that could fix the issue you encountered.

**Comment by Szym29** [comment]
@HelloWorldLTY I recently re-wrote all codes using Pytorch and uploaded them to https://github.com/Szym29/UNAGI_torch. If you are interested in our repo, you can jump to another repo. I will update this repo once everything is done.
