### ISSUE TITLE
How to kown iDREM  result track = '10-0n4-2n4n6-0n1n4n10n12' belong to which cell clusters or populations

### ISSUE THREAD

**Issue by qingchen36** [mcgilldinglab/UNAGI#4]
Dear Mr Zheng，
For single-cell transcriptome time-series analysis, one aspect focuses on the genes expression changes of genes across different time points, while the other aspect aims to investigate the cell types influence  within a particular track.

In the article "UNAGI can effectively reconstruct the cellular dynamics associated with time series or disease progression data based on the cell embeddings learned by the model. Within our analytical framework, a "track" delineates a distinct trajectory within the reconstructed dynamics graph, marking the sequential cellular state transitions corresponding to specific cell clusters or populations. These tracks not only identify pathways but also chronicle the journey of cellular progression and evolution. Within mesenchymal cells, we have discerned 10 distinct progression tracks (Fig. 3a)."  Fig.3a also in http://dinglab.rimuhc.ca/unagi/.

question1: Which part of the analysis results from UNAGI corresponds to Fig 3a, and is it possible to further develop it?
question2: Dose the iDREM  result tracks corresponds to Fig 3a?
question3: How to get the relationship between the track and cell types?

thank you!
ShengChen

**Comment by Szym29** [comment]
Hi Shengchen,

Thanks for your interest in UNAGI. For your question1, Fig. 3a is the dynamics graph built by UNAGI and it shows the IPF temporal progression from the perspective of cell populations. The UNAGI produces edges and node information and saves them in 'attribute.pkl' file with the key 'edges', and 'clusterType'. Fig. 3a was drawn manually based on these information. Although adding a function that can graphically visualize the dynamics graph is not our priority, you can use the following snippet to visualize these tracks. 
```python
From UNAGI.utils import visualize_dynamic_graphs_by_text
import pickle as pkl
uns = pkl.load(open('attribute.pkl','rb')) #attribute.pkl is the pickle file produced by UNAGI.
visualize_dynamic_graphs_by_text(uns['edges'],uns['clusterType'])
```
Here is the example output of the text visualized track 17 (FibAdv-17 in our manuscript). You can find the track, stage, cluster id and cell type of the cluster information from the output. e.g. Stage 3|-- 17_FibroblastAdventitial-> cluster 17 from stage 3 is FibroblastAdventitial and it is a child of 14_FibroblastAdventitial in stage 2. 
```text
Track 17 :
Stage 0|-- 17_FibroblastAdventitial
    Stage 1|-- 18_FibroblastAdventitial
        Stage 2|-- 14_FibroblastAdventitial
            Stage 3|-- 17_FibroblastAdventitial
    Stage 1|-- 20_FibroblastAirway
        Stage 2|-- 19_FibroblastAirway
            Stage 3|-- 20_FibroblastAirway
    Stage 1|-- 22_FibroblastFibrotic
        Stage 2|-- 20_FibroblastFibrotic
            Stage 3|-- 10_FibroblastFibrotic
```

For your second question 

> Dose the iDREM result tracks corresponds to Fig 3a?

Yes, the iDREM produces temporal GRNs (gene regulatory networks) of tracks shown in Fig. 3a. e.g. Fig. 3b is the temporal GRNs of FibAlv-4 track. But nodes in iDREM are not the same as nodes in Fig. 3a. Nodes in Fig. 3a are cell populations, but nodes in iDREM results are a set of co-expression genes.

For your last question 
> How to get the relationship between the track and cell types?

UNAGI has the built-in functions for this part, and using the visualization functions from my answer1, you should be able to understand cell type changes in each track. 

I hope these help.

Thanks,
Yumin

**Comment by qingchen36** [comment]
The information " 'attribute.pkl' file with the key 'edges', and 'clusterType' " is just i wanted to know.
Thank you！！！

**Comment by Szym29** [comment]
Hi @qingchen36 ,

uns['edges'] is a dictionary, with stage id as the key, and the value is a nested list containing the edge information. 
e.g. {'0':[[1,2],[2,5],[3,4]], '0' is the stage id, [[1,2],[2,5],[3,4]] is the edges info. [a, b] is the edge connecting cluster a in stage 0 and cluster b is the stage 1. if the key is `n`, then the nested list containing edges connecting between stage `n` and stage `n+1`.

uns['clusterType'] is also a dictionary, key is the stage id and values is a list of cell type for corresponding leiden clusters. e.g. {'0': [CD4T, CD8T, Marcophage, CD16Monocyte, CD14Monocyte]}, then the cell type of stage 0 leiden cluster 0 is CD4T,  stage 0 leiden cluster 1 is CD8T, stage 0 leiden cluster 2 is Marcophage, stage 0 leiden cluster 3 is CD16Monocyte, and stage 0 leiden cluster 3 is CD14Monocyte.

I hope these help.

Thanks,
Yumin
